package main

import (
	"crypto/tls"
)

type Cipher struct {
        Name            string
        Tlscode         uint16
        Rfc             string
        Csinfolink      string
        Csinfoapi       string
        Tlsminversion   string
        Tlsmaxversion   string
        Gocryptonative  bool
        Gocryptocipher  uint16
        Gocryptomintlsv uint16
        Gocryptomaxtlsv uint16
}

func GetCiphers() (ciphers []Cipher) {
        // golang native tls does only implement a subset
        ciphers = []Cipher{
                // TLS1.3
                Cipher{
                        Name:            "TLS_AES_256_GCM_SHA384",
                        Rfc:             "8446",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_AES_256_GCM_SHA384/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_AES_256_GCM_SHA384/",
                        Tlsminversion:   "TLS1.3",
                        Tlsmaxversion:   "TLS1.3",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_AES_256_GCM_SHA384,
                        Gocryptomintlsv: tls.VersionTLS13,
                        Gocryptomaxtlsv: tls.VersionTLS13,
                },
                Cipher{
                        Name:            "TLS_AES_128_GCM_SHA256",
                        Rfc:             "8446",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_AES_128_GCM_SHA256/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_AES_128_GCM_SHA256/",
                        Tlsminversion:   "TLS1.3",
                        Tlsmaxversion:   "TLS1.3",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_AES_128_GCM_SHA256,
                        Gocryptomintlsv: tls.VersionTLS13,
                        Gocryptomaxtlsv: tls.VersionTLS13,
                },
                Cipher{
                        Name:            "TLS_CHACHA20_POLY1305_SHA256",
                        Rfc:             "8446",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_CHACHA20_POLY1305_SHA256/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_CHACHA20_POLY1305_SHA256/",
                        Tlsminversion:   "TLS1.3",
                        Tlsmaxversion:   "TLS1.3",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_CHACHA20_POLY1305_SHA256,
                        Gocryptomintlsv: tls.VersionTLS13,
                        Gocryptomaxtlsv: tls.VersionTLS13,
                },
                // others
                Cipher{
                        Name:            "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
                        Rfc:             "7905",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256/",
                        Tlsminversion:   "TLS1.2",
                        Tlsmaxversion:   "TLS1.2",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
                        Gocryptomintlsv: tls.VersionTLS12,
                        Gocryptomaxtlsv: tls.VersionTLS12,
                },
                Cipher{
                        Name:            "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
                        Rfc:             "7905",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256/",
                        Tlsminversion:   "TLS1.2",
                        Tlsmaxversion:   "TLS1.2",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
                        Gocryptomintlsv: tls.VersionTLS12,
                        Gocryptomaxtlsv: tls.VersionTLS12,
                },
                Cipher{
                        Name:            "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
                        Rfc:             "5289",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384/",
                        Tlsminversion:   "TLS1.2",
                        Tlsmaxversion:   "TLS1.2",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
                        Gocryptomintlsv: tls.VersionTLS12,
                        Gocryptomaxtlsv: tls.VersionTLS12,
                },
                Cipher{
                        Name:            "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
                        Rfc:             "5289",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384/",
                        Tlsminversion:   "TLS1.2",
                        Tlsmaxversion:   "TLS1.2",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
                        Gocryptomintlsv: tls.VersionTLS12,
                        Gocryptomaxtlsv: tls.VersionTLS12,
                },
                Cipher{
                        Name:            "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
                        Rfc:             "5289",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256/",
                        Tlsminversion:   "TLS1.2",
                        Tlsmaxversion:   "TLS1.2",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
                        Gocryptomintlsv: tls.VersionTLS12,
                        Gocryptomaxtlsv: tls.VersionTLS12,
                },
                Cipher{
                        Name:            "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
                        Rfc:             "5289",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256/",
                        Tlsminversion:   "TLS1.2",
                        Tlsmaxversion:   "TLS1.2",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
                        Gocryptomintlsv: tls.VersionTLS12,
                        Gocryptomaxtlsv: tls.VersionTLS12,
                },
                Cipher{
                        Name:            "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
                        Rfc:             "5289",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256/",
                        Tlsminversion:   "TLS1.2",
                        Tlsmaxversion:   "TLS1.2",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,
                        Gocryptomintlsv: tls.VersionTLS12,
                        Gocryptomaxtlsv: tls.VersionTLS12,
                },
                Cipher{
                        Name:            "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
                        Rfc:             "5289",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256/",
                        Tlsminversion:   "TLS1.2",
                        Tlsmaxversion:   "TLS1.2",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,
                        Gocryptomintlsv: tls.VersionTLS12,
                        Gocryptomaxtlsv: tls.VersionTLS12,
                },
                Cipher{
                        Name:            "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
                        Rfc:             "8422",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA/",
                        Tlsminversion:   "TLS1.0",
                        Tlsmaxversion:   "TLS1.2",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
                        Gocryptomintlsv: tls.VersionTLS10,
                        Gocryptomaxtlsv: tls.VersionTLS12,
                },
                Cipher{
                        Name:            "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
                        Rfc:             "8422",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA/",
                        Tlsminversion:   "TLS1.0",
                        Tlsmaxversion:   "TLS1.2",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
                        Gocryptomintlsv: tls.VersionTLS10,
                        Gocryptomaxtlsv: tls.VersionTLS12,
                },
                Cipher{
                        Name:            "TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA",
                        Rfc:             "8422",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA/",
                        Tlsminversion:   "TLS1.0",
                        Tlsmaxversion:   "TLS1.1",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,
                        Gocryptomintlsv: tls.VersionTLS10,
                        Gocryptomaxtlsv: tls.VersionTLS11,
                },
                Cipher{
                        Name:            "TLS_ECDHE_RSA_WITH_RC4_128_SHA",
                        Rfc:             "8422",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_ECDHE_RSA_WITH_RC4_128_SHA/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_ECDHE_RSA_WITH_RC4_128_SHA/",
                        Tlsminversion:   "TLS1.0",
                        Tlsmaxversion:   "TLS1.2",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_ECDHE_RSA_WITH_RC4_128_SHA,
                        Gocryptomintlsv: tls.VersionTLS10,
                        Gocryptomaxtlsv: tls.VersionTLS12,
                },
                Cipher{
                        Name:            "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
                        Rfc:             "8422",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA/",
                        Tlsminversion:   "TLS1.0",
                        Tlsmaxversion:   "TLS1.2",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
                        Gocryptomintlsv: tls.VersionTLS10,
                        Gocryptomaxtlsv: tls.VersionTLS12,
                },
                Cipher{
                        Name:            "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
                        Rfc:             "8422",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA/",
                        Tlsminversion:   "TLS1.0",
                        Tlsmaxversion:   "TLS1.2",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
                        Gocryptomintlsv: tls.VersionTLS10,
                        Gocryptomaxtlsv: tls.VersionTLS12,
                },
                Cipher{
                        Name:            "TLS_ECDHE_ECDSA_WITH_RC4_128_SHA",
                        Rfc:             "8422",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA/",
                        Tlsminversion:   "TLS1.0",
                        Tlsmaxversion:   "TLS1.2",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_ECDHE_ECDSA_WITH_RC4_128_SHA,
                        Gocryptomintlsv: tls.VersionTLS10,
                        Gocryptomaxtlsv: tls.VersionTLS12,
                },
                Cipher{
                        Name:            "TLS_RSA_WITH_AES_256_GCM_SHA384",
                        Rfc:             "5288",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_RSA_WITH_AES_256_GCM_SHA384/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_RSA_WITH_AES_256_GCM_SHA384/",
                        Tlsminversion:   "TLS1.2",
                        Tlsmaxversion:   "TLS1.2",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_RSA_WITH_AES_256_GCM_SHA384,
                        Gocryptomintlsv: tls.VersionTLS12,
                        Gocryptomaxtlsv: tls.VersionTLS12,
                },
                Cipher{
                        Name:            "TLS_RSA_WITH_AES_128_GCM_SHA256",
                        Rfc:             "5288",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_RSA_WITH_AES_128_GCM_SHA256/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_RSA_WITH_AES_128_GCM_SHA256/",
                        Tlsminversion:   "TLS1.2",
                        Tlsmaxversion:   "TLS1.2",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_RSA_WITH_AES_128_GCM_SHA256,
                        Gocryptomintlsv: tls.VersionTLS12,
                        Gocryptomaxtlsv: tls.VersionTLS12,
                },
                Cipher{
                        Name:            "TLS_RSA_WITH_AES_128_CBC_SHA256",
                        Rfc:             "5246",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_RSA_WITH_AES_128_CBC_SHA256/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_RSA_WITH_AES_128_CBC_SHA256/",
                        Tlsminversion:   "TLS1.2",
                        Tlsmaxversion:   "TLS1.2",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_RSA_WITH_AES_128_CBC_SHA256,
                        Gocryptomintlsv: tls.VersionTLS12,
                        Gocryptomaxtlsv: tls.VersionTLS12,
                },
                Cipher{
                        Name:            "TLS_RSA_WITH_AES_256_CBC_SHA",
                        Rfc:             "5246",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_RSA_WITH_AES_256_CBC_SHA/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_RSA_WITH_AES_256_CBC_SHA/",
                        Tlsminversion:   "TLS1.0",
                        Tlsmaxversion:   "TLS1.2",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_RSA_WITH_AES_256_CBC_SHA,
                        Gocryptomintlsv: tls.VersionTLS10,
                        Gocryptomaxtlsv: tls.VersionTLS12,
                },
                Cipher{
                        Name:            "TLS_RSA_WITH_AES_128_CBC_SHA",
                        Rfc:             "5246",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_RSA_WITH_AES_128_CBC_SHA/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_RSA_WITH_AES_128_CBC_SHA/",
                        Tlsminversion:   "TLS1.0",
                        Tlsmaxversion:   "TLS1.2",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_RSA_WITH_AES_128_CBC_SHA,
                        Gocryptomintlsv: tls.VersionTLS10,
                        Gocryptomaxtlsv: tls.VersionTLS12,
                },
                Cipher{
                        Name:            "TLS_RSA_WITH_3DES_EDE_CBC_SHA",
                        Rfc:             "5246",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_RSA_WITH_3DES_EDE_CBC_SHA/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_RSA_WITH_3DES_EDE_CBC_SHA/",
                        Tlsminversion:   "TLS1.0",
                        Tlsmaxversion:   "TLS1.1",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_RSA_WITH_3DES_EDE_CBC_SHA,
                        Gocryptomintlsv: tls.VersionTLS10,
                        Gocryptomaxtlsv: tls.VersionTLS11,
                },
                Cipher{
                        Name:            "TLS_RSA_WITH_RC4_128_SHA",
                        Rfc:             "5246",
                        Csinfolink:      "https://ciphersuite.info/cs/TLS_RSA_WITH_RC4_128_SHA/",
                        Csinfoapi:       "https://ciphersuite.info/api/cs/TLS_RSA_WITH_RC4_128_SHA/",
                        Tlsminversion:   "TLS1.0",
                        Tlsmaxversion:   "TLS1.2",
                        Gocryptonative:  true,
                        Gocryptocipher:  tls.TLS_RSA_WITH_RC4_128_SHA,
                        Gocryptomintlsv: tls.VersionTLS10,
                        Gocryptomaxtlsv: tls.VersionTLS12,
                },
        }
        return ciphers
}

